### ISSUE TITLE
Master Issue @emsesc

### ISSUE THREAD

**Issue by emsesc** [bitprj/intro-to-k8s-fcc#1]
- [ ] Slim down tinyhats (no s3 version)
- [ ] Instructions for `manipulate-service`
- [ ] Instructions for `mysql` instance
- [ ] Instructions for `fetch-service`
- [ ] Instructions for `gateway-service`

Slim version:
* Less files for simplicity
* Little code as possible
